### ISSUE TITLE
DvXray_train.txt 数据集里面没有这个文件

### ISSUE THREAD

**Issue by xyb1314** [Mbwslib/DvXray#1]
作者你好！我想问一下这是需要怎么获取这个文件，还是通过数据集来生产的？？？

**Comment by xyb1314** [comment]
looking forward to update this file thx!

**Comment by Mbwslib** [comment]
我们已经更新了数据集，将positive sample和negative sample下载下来放在一个文件夹，运行get_split.py即可

**Comment by xyb1314** [comment]
感谢，祝你们科研顺利，顶刊发发发！

&nbsp;


***@***.***
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年3月27日(星期三) 上午10:55
收件人: ***@***.***&gt;; 
抄送: ***@***.******@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Mbwslib/DvXray] DvXray_train.txt 数据集里面没有这个文件 (Issue #1)





 
我们已经更新了数据集，将positive sample和negative sample下载下来放在一个文件夹，运行get_split.py即可
